# Generated by Django 4.1.5 on 2023-01-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('housename', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('landmark', models.CharField(max_length=40)),
                ('pin', models.BigIntegerField()),
                ('subject', models.CharField(max_length=40)),
            ],
        ),
    ]
